Narzedzia #2 homework
coders-school/resolvable-conflict pull request #10
Opened 2020-05-27 19:38 UTC by mariuszlisowski

All tasks done, although I had have some difficulties with the last one, i.e. cherry-pick, more closely with a 'hard reset' of 'vimtutor' branch. Thanks to Lukin's hint finally the job was done. Not sure whether it's all correct, but hope so :) But why can't it be automatically merged?

2020-05-31 10:37 UTC, Kasperice approved these changes
Solution looks good for me

2020-06-02 09:22 UTC, Marcinati approved these changes
Everything is allright.

2020-06-02 09:34 UTC, Marcinati requested changes
Everything is allright.

2020-06-02 09:34 UTC, Marcinati commented on src/functions.cpp
> +#include <algorithm>
Sort headers.

2020-06-02 09:56 UTC, mariuszlisowski commented on src/functions.cpp
> +#include <algorithm>
Done. Thank you!

2020-06-02 10:01 UTC, Marcinati approved these changes
Now everything is allright. :)

2020-06-02 13:50 UTC, ziobron commented
It can't be merged automatically because I've also added correction on master - missing <algorithm> header.

+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

2020-06-02 13:50 UTC, closed without merging