Tools #2 git, vim, compilers
coders-school/resolvable-conflict pull request #11
Opened 2020-05-27 22:52 UTC by NeoBauer

2020-05-30 15:22 UTC, DamiXioR reviewed
have a nice day!

2020-05-30 15:22 UTC, DamiXioR commented on src/functions.cpp
> +    for (unsigned int i = 0; i < numbers.size(); ++i) {
use std::size_t with arrays etc.

2020-05-30 15:22 UTC, DamiXioR commented on Makefile
> +	g++ -std=c++17 -Wall -Wextra -pedantic -Wconversion -Werror -Iinc/ src/*.cpp  -o main
-I./inc looks better

2020-05-30 15:22 UTC, DamiXioR commented on src/functions.cpp
> +#include "functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
unnecessary comments

2020-05-30 15:22 UTC, DamiXioR commented on src/main.cpp
> +#include "functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
unnecessary comments

2020-06-02 09:34 UTC, Marcinati requested changes

2020-06-02 09:34 UTC, Marcinati commented on src/functions.cpp
> +#include <algorithm>
Sort headers.

2020-06-02 13:56 UTC, ziobron commented on tutor.txt
> +--->  7)  And so are you.
not completed

2020-06-02 13:56 UTC, ziobron commented on tutor.txt
> +---> thee best time to see thee flowers is in thee spring.
not completed

2020-06-02 13:56 UTC, ziobron commented on Makefile
> +	g++ -std=c++17 -Iinc/ src/*.cpp  -o main
it should be done after merging

2020-06-02 13:57 UTC, ziobron commented
Anyway - max points
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

2020-06-02 13:57 UTC, closed without merging