Homework tools#2
coders-school/resolvable-conflict pull request #13
Opened 2020-05-28 14:21 UTC by piezol

2020-05-30 08:31 UTC, Kasperice approved these changes
Solution looks good

2020-05-30 15:16 UTC, DamiXioR reviewed
nice work

2020-05-30 15:16 UTC, DamiXioR commented on Makefile
> +	g++ -std=c++17 src/*.cpp -Iinc/ -Wall -Wextra -pedantic -Werror -o main
in my opinion include directory flag looks better in this way: -I./inc

2020-06-02 09:36 UTC, Marcinati requested changes

2020-06-02 09:36 UTC, Marcinati commented on src/functions.cpp
> +#include <algorithm>
Sort headers.

2020-06-02 14:59 UTC, ziobron commented on tutor
> +---> thee best time to see thee flowers is in thee spring.
missing lesson ;)

2020-06-02 15:00 UTC, ziobron commented
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

2020-06-02 15:00 UTC, closed without merging