Homework Tools #2
coders-school/resolvable-conflict pull request #14
Opened 2020-05-28 14:32 UTC by jakjan95

Solution to homework from tools lesson

2020-05-30 08:30 UTC, Kasperice commented on Makefile
> +	g++ -std=c++17 -Werror -Iinc/  src/*.cpp -o main
you can consider using more flags: -Wall -Wextra -pedantic

2020-05-30 08:30 UTC, Kasperice commented on src/functions.cpp
>  #include "../inc/functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
It should be also changed to `#include "functions.hpp"`

2020-06-02 09:40 UTC, Marcinati requested changes

2020-06-02 09:40 UTC, Marcinati commented on src/functions.cpp
> +#include <algorithm>
You have proper flag (-Iinc/), so as Kasperice says, you can add headers straight by name.
Second case: sort headers. ;)

2020-06-02 15:03 UTC, ziobron requested changes

2020-06-02 15:03 UTC, ziobron commented on Makefile
> +	g++ -std=c++17 -Werror  src/*.cpp -o main
Not only `-Werror` should be added. Please add `-Wall -Wextra -pedantic -Wconversion`

2020-06-02 18:50 UTC, DamiXioR reviewed
nice work

2020-06-02 18:50 UTC, DamiXioR commented on src/functions.cpp
>      for (int i = 0; i < numbers.size(); ++i) {
you should use size_t

2020-06-02 18:50 UTC, DamiXioR commented on Makefile
> +	g++ -std=c++17 -Werror -Iinc/  src/*.cpp -o main
-I. /inc looks better

2020-06-03 12:41 UTC, ziobron commented
Great!

+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

2020-06-03 12:41 UTC, closed without merging