Homework "Narzędzia #2: git, vim, kompilatory"
coders-school/resolvable-conflict pull request #43
Opened 2020-06-04 20:02 UTC by kari0036

2020-06-04 20:20 UTC, DamiXioR reviewed
some ideas

2020-06-04 20:20 UTC, DamiXioR commented on src/functions.cpp
> +#include "functions.hpp"
in my opinion you removed min function

2020-06-04 20:20 UTC, DamiXioR commented on src/functions.cpp
> +    for (size_t i = 0; i < numbers.size(); ++i) {
looks better if you use size_t with std::

2020-06-04 20:20 UTC, DamiXioR commented on src/main.cpp
> +#include "functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
remove comments

2020-06-04 20:20 UTC, DamiXioR commented on Makefile
> +	g++ -std=c++17 src/*.cpp -Wall -Iinc -Wextra -pedantic -Werror -Wconversion -O3 -g -o main
-I./inc looks better

2020-06-05 13:45 UTC, Marcinati requested changes
1. Files name should be a "tutor" instead of Test.
2. Removing any functionality of program (here: minimum) was forbidden, you should restore this.

2020-06-05 15:12 UTC, ziobron requested changes
Judging from the commit names you have not done merges properly. They are named "marge" (with typo), so probably it was your own message. Please try doing it once again, maybe from a clean repo. You can just use the existing tutor file, just copy it to a new instance of this repo.

2020-06-05 15:12 UTC, ziobron commented on inc/functions.hpp
> -int min(std::vector<int> const &);
You shouldn't remove min function.

2020-06-05 15:12 UTC, ziobron commented on Test
> +>>>>>>> vimtutor
Your merge was not successful. Please fix it. If you need help let us know on Discord.
+ the name of this file should be tutor.

2020-06-07 14:40 UTC, ziobron requested changes

2020-06-07 14:40 UTC, ziobron commented on src/functions.cpp
> -    return minimum;
min function and it's usage is still removed. Please bring this function back.

2020-06-07 14:40 UTC, ziobron commented on src/main.cpp
> -    std::cout << "Minimum: " << minimum << '\n';
Bring back usage of min

2020-06-07 16:36 UTC, ziobron requested changes
Now reverse function is missing. We want both reverse and min :)

2020-06-07 16:36 UTC, ziobron commented on src/functions.cpp
> -
But now reverse function is gone! We want them both :)

2020-06-07 17:58 UTC, ziobron approved these changes

2020-06-07 17:58 UTC, ziobron commented
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

2020-06-07 17:58 UTC, closed without merging