Homework2 tools
coders-school/resolvable-conflict pull request #45
Opened 2020-06-05 13:05 UTC by danielzwierz

2020-06-05 13:38 UTC, Marcinati approved these changes

2020-06-05 15:16 UTC, ziobron requested changes
It looks that you have not completed vimtutor. I can't see changes in this file. Please deliver them :)

2020-06-05 15:16 UTC, ziobron commented on vimtutor
> +---> The ccow jumpedd ovverr thhe mooon.
not completed

2020-06-05 15:16 UTC, ziobron commented on vimtutor
> +---> There is text misng this .
not completed

2020-06-05 15:16 UTC, ziobron commented on vimtutor
> +     There is also some text missing here.
not completed

2020-06-07 14:34 UTC, ziobron commented
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

2020-06-07 14:34 UTC, closed without merging