Tools #2.
coders-school/resolvable-conflict pull request #49
Opened 2020-06-06 14:29 UTC by kali-03

2020-06-06 16:20 UTC, Pawellos commented on functions.cpp
> +    for (int i = 0; i < numbers.size(); ++i) {
I think you should use size_t unless int

2020-06-06 16:20 UTC, Pawellos commented on functions.cpp
> +    for (int i = 0; i < numbers.size(); ++i) {
I supposed if you would add more flags it will be warning/error

2020-06-06 16:20 UTC, Pawellos commented on Makefile
> +	g++ -std=c++17 src/*.cpp -Werror -I./src -I./inc -o main
You could add more flags. Like -Wall -Wextra -pedantic -Wconversion

2020-06-06 16:52 UTC, Marcinati commented on functions.cpp
> +#include <algorithm>
Sort headers.

2020-06-06 16:53 UTC, Marcinati commented on src/functions.cpp
> +#include "functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
Delete comment.

2020-06-06 16:53 UTC, Marcinati commented on src/main.cpp
> +#include "functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
Sort headers & delete comment.

2020-06-06 19:52 UTC, Kasperice requested changes
As I remember file "functions.cpp" should not be included in solution. Its content should be moved to `src/functions.cpp`

2020-06-07 16:40 UTC, ziobron requested changes

2020-06-07 16:40 UTC, ziobron commented on src/main.cpp
> +
Where is reverse function? It's gone. It wasn't merged properly. We want both min and reverse functions.

2020-06-07 17:37 UTC, DamiXioR reviewed
Good job

2020-06-07 17:37 UTC, DamiXioR commented on src/functions.cpp
> +#include "functions.hpp"
you should move include header on the top

2020-06-07 19:49 UTC, ziobron commented
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

2020-06-07 19:49 UTC, closed without merging