Homework
coders-school/resolvable-conflict pull request #59
Opened 2020-06-15 15:42 UTC by MPrzem

Pull request with done homework

2020-06-16 09:17 UTC, Marcinati commented on Makefile
> +	g++ -std=c++17 -Werror -Iinc src/*.cpp -o main
You can add more compile flag, like:  ```-Wall -Wextra -pedantic -Wconversion -O3```

2020-06-16 09:20 UTC, Marcinati commented on src/main.cpp
>  #include "../inc/functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
You have included functions in previous line, you can delete this line and comment above.

2020-06-16 09:21 UTC, Marcinati commented on tutor
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ok. :)

2020-06-16 09:26 UTC, Marcinati requested changes
If you will add more compile flags and add some improvements it'll be allright.

2020-06-16 09:26 UTC, Marcinati commented on src/functions.cpp
>  #include <limits>
Please, sort headers and remove comment.

2020-06-16 09:26 UTC, Marcinati commented on src/functions.cpp
>  void print(std::vector<int> const & numbers) {
Is this for loop work with int i? I'm strongly recommend to use size_t instead of int.

2020-06-16 17:07 UTC, DamiXioR reviewed
If you add more compile flags you will be alerted about use std::size_t or unsigned int instead int.

2020-06-18 06:15 UTC, ziobron requested changes
Not everything is completed in vimtutor. Also there are some compilation flags missing `-Wall -Wextra -pedantic -Wconversion -O3` as Marcinati suggested. Please deliver them :)

2020-06-18 06:15 UTC, ziobron commented on tutor
> +--->  7)  And so are you.
not completed

2020-06-18 06:15 UTC, ziobron commented on tutor
> +---> Fiix the errors oon thhis line and reeplace themRRRtth undo.
not completed

2020-06-18 06:15 UTC, ziobron commented on tutor
> +---> This line has a few words that need changing using the change operator.
not completed

2020-06-18 06:15 UTC, ziobron commented on tutor
> +---> The end of this line needs to be corrected using the  c$  command.
not completed

2020-06-18 06:15 UTC, ziobron commented on tutor
> +---> thee best time to see thee flowers is in thee spring.
not completed

2020-06-18 17:46 UTC, MPrzem commented
> You left comment. ;)

Thanks for review. Could you tell me where i've left comment?

2020-06-19 05:53 UTC, ziobron commented on src/main.cpp
>  #include "functions.hpp"    // TODO: add proper compilation flag and change to #include "functions.hpp"
Here is a // TODO comment. You can/should remove it when this job is done :)

2020-06-19 05:53 UTC, ziobron approved these changes

2020-06-19 05:54 UTC, ziobron commented
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick

{ "requirement_ids": [1999, 2000, 2001, 2002], "points": [4, 5, 4, 3] }

2020-06-19 05:54 UTC, closed without merging